# Generated by Django 3.2.5 on 2021-07-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('email', models.EmailField(blank=True, default='', max_length=40, primary_key=True, serialize=False, verbose_name='email')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='name')),
                ('surname', models.CharField(blank=True, max_length=20, null=True, verbose_name='surname')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnReason',
            fields=[
                ('name', models.CharField(blank=True, default='', max_length=20, primary_key=True, serialize=False, verbose_name='Return reason')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnState',
            fields=[
                ('name', models.CharField(blank=True, default='', max_length=20, primary_key=True, serialize=False, verbose_name='Return state')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Rma',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='RMA number')),
                ('order_number', models.CharField(max_length=50, null=True, verbose_name='Order number')),
                ('date_received', models.DateTimeField(verbose_name='Date received')),
                ('customer_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpad.customer')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpad.returnstate')),
            ],
        ),
    ]
