# Generated by Django 3.2.5 on 2021-07-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpad', '0005_alter_device_gtin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='gtin',
            field=models.PositiveIntegerField(blank=True, verbose_name='gtin'),
        ),
    ]
