# Generated by Django 3.2.5 on 2021-07-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpad', '0006_alter_device_gtin'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='size_of_the_device',
            field=models.PositiveIntegerField(blank=True, default='0', null=True, verbose_name='size of device in cm'),
        ),
        migrations.AlterField(
            model_name='device',
            name='price_of_device',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=8, max_length=100, null=True, verbose_name='device price in €'),
        ),
        migrations.AlterField(
            model_name='device',
            name='weight_of_the_device',
            field=models.PositiveIntegerField(blank=True, default='0', null=True, verbose_name='weight of device in kg'),
        ),
    ]
