# Generated by Django 3.1.7 on 2021-07-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpad', '0007_auto_20210706_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
